### ISSUE TITLE
όχι μαζί await και callbacks!

### ISSUE THREAD

**Issue by tmanolat** [ApostolisHD/React-Express-CRUD#1]
https://github.com/ApostolisHD/React-Express-CRUD/blob/17ab044c7b49c9e39ba88d8fb2aca858ce9d7965/server/Routes.js#L21

**Comment by ApostolisHD** [comment]
https://github.com/ApostolisHD/React-Express-CRUD/blob/56dd55a17e9c0144c6534d420f751b82218bf7b2/server/queries.js#L22
