### ISSUE TITLE
leave in package.json ONLY the needed libs! - cleanup your package.json!

### ISSUE THREAD

**Issue by tmanolat** [ApostolisHD/React-Express-CRUD#4]
https://github.com/ApostolisHD/React-Express-CRUD/blob/17ab044c7b49c9e39ba88d8fb2aca858ce9d7965/server/package.json#L23

**Comment by ApostolisHD** [comment]
https://github.com/ApostolisHD/React-Express-CRUD/blob/56dd55a17e9c0144c6534d420f751b82218bf7b2/server/package.json#L11
