### ISSUE TITLE
is "pool" a right name for the variable? confusing with pg connection pooling...

### ISSUE THREAD

**Issue by tmanolat** [ApostolisHD/React-Express-CRUD#6]
https://github.com/ApostolisHD/React-Express-CRUD/blob/17ab044c7b49c9e39ba88d8fb2aca858ce9d7965/server/index.js#L3

**Comment by ApostolisHD** [comment]
https://github.com/ApostolisHD/React-Express-CRUD/blob/56dd55a17e9c0144c6534d420f751b82218bf7b2/server/index.js#L3
