### ISSUE TITLE
format your JSX! make hierarchies clear....

### ISSUE THREAD

**Issue by tmanolat** [ApostolisHD/React-Express-CRUD#7]
https://github.com/ApostolisHD/React-Express-CRUD/blob/17ab044c7b49c9e39ba88d8fb2aca858ce9d7965/client/src/App.js#L11

**Comment by ApostolisHD** [comment]
https://github.com/ApostolisHD/React-Express-CRUD/blob/56dd55a17e9c0144c6534d420f751b82218bf7b2/client/src/App.js#L10
